name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for publishing docs
      id-token: write # Needed for creating provenance attestation
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
      - run: pnpm i -r
      - run: npm run build
      - name: Get version of the project
        id: vvver
        uses: 'euberdeveloper/ga-project-version@main'
      - run: npm pkg delete devDependencies scripts pnpm browserslist packageManager
      - name: Create Docs
        if: contains(steps.vvver.outputs.version, 'pre') == false
        run: npm run docs
      - name: Deploy Docs
        if: contains(steps.vvver.outputs.version, 'pre') == false
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          publish_branch: docs
      - run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
